// <auto-generated />
using System;
using Demo_Omar_Emad_Hamdy_Senior3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo_Omar_Emad_Hamdy_Senior3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtPieceCategory", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("PiecesId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "PiecesId");

                    b.HasIndex("PiecesId");

                    b.ToTable("ArtPieceCategory");
                });

            modelBuilder.Entity("Demo_Omar_Emad_Hamdy_Senior3.Models.ArtPiece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("Price")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Pieces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 2,
                            Description = "Egyptian art",
                            Price = 250m,
                            Title = "Sheks"
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 3,
                            Description = "French art",
                            Price = 500m,
                            Title = "Monor"
                        });
                });

            modelBuilder.Entity("Demo_Omar_Emad_Hamdy_Senior3.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Arts"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Photoes"
                        });
                });

            modelBuilder.Entity("Demo_Omar_Emad_Hamdy_Senior3.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "omar.052302@gmail.com",
                            Name = "Omar",
                            Phone = "012293215"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ahmed@gmail.com",
                            Name = "Ahmed",
                            Phone = "012293288"
                        },
                        new
                        {
                            Id = 3,
                            Email = "kareem@gmail.com",
                            Name = "Kareem",
                            Phone = "0125899"
                        });
                });

            modelBuilder.Entity("Demo_Omar_Emad_Hamdy_Senior3.Models.LoyaltyCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("LoyaltyCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 555m,
                            CardNumber = "1a1",
                            CustomerId = 1
                        },
                        new
                        {
                            Id = 2,
                            Balance = 1000m,
                            CardNumber = "22a",
                            CustomerId = 2
                        });
                });

            modelBuilder.Entity("ArtPieceCategory", b =>
                {
                    b.HasOne("Demo_Omar_Emad_Hamdy_Senior3.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demo_Omar_Emad_Hamdy_Senior3.Models.ArtPiece", null)
                        .WithMany()
                        .HasForeignKey("PiecesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Demo_Omar_Emad_Hamdy_Senior3.Models.ArtPiece", b =>
                {
                    b.HasOne("Demo_Omar_Emad_Hamdy_Senior3.Models.Customer", "Customer")
                        .WithMany("ArtPieces")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Demo_Omar_Emad_Hamdy_Senior3.Models.LoyaltyCard", b =>
                {
                    b.HasOne("Demo_Omar_Emad_Hamdy_Senior3.Models.Customer", "Customer")
                        .WithOne("LoyaltyCard")
                        .HasForeignKey("Demo_Omar_Emad_Hamdy_Senior3.Models.LoyaltyCard", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Demo_Omar_Emad_Hamdy_Senior3.Models.Customer", b =>
                {
                    b.Navigation("ArtPieces");

                    b.Navigation("LoyaltyCard")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
